src/Site/Bundle/PlatformBundle/Entity/User.php
<?php


namespace Site\Bundle\PlatformBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Site\Bundle\PlatformBundle\lib\MyConst;

/**
 * @ORM\Entity(repositoryClass="Site\Bundle\PlatformBundle\Entity\UserRepository")
 * @ORM\Table(name="user")
 */
class User implements UserInterface, \Serializable

{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     *
     * @var integer $id
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length=100, name="username")
     *
     * @var string $username
     */
    protected $username;


    /**
     * @ORM\Column(type="string", length=255,name="email")
     *
     * @var string $email
     */
    protected $email;

    /**
     * @ORM\Column(type="string", length=255 ,name="password")
     *
     * @var string $password
     */

    protected $password;

    /**
     * @ORM\Column(type="datetime", name="created_at")
     *
     * @var \DateTime $createdAt
     */

    protected $createdAt;


    /**
     * @ORM\OneToMany(targetEntity="Requirement", mappedBy="contact")
     */
    protected $requirement;

    /**
     * @ORM\OneToMany(targetEntity="Resource", mappedBy="contact")
     */
    protected $resource;


    /**
     * @ORM\Column(type="string", length=255,name="department")
     *
     * @var string $department
     */
    protected $department;

    /**
     * @ORM\Column(type="string", length=255,name="location")
     *
     * @var string $location
     */
    protected $location;


    /**
     * @ORM\Column(type="string", length=255,name="phone")
     *
     * @var string $phone
     */
    protected $phone;

    /**
     * @ORM\Column(type="string", length=255,name="hupu_account")
     *
     * @var string $hupuAccount
     */
    protected $hupuAccount;


    /**
     * Constructs a new instance of User
     */
    public function __construct()
    {
        $this->requirement = new ArrayCollection();
        $this->createdAt = new \DateTime();
    }



    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }



    /**
     * Set email
     *
     * @param string $email
     * @return User
     */
    public function setEmail($email)
    {
        $this->email = $email;

        return $this;
    }

    /**
     * Get email
     *
     * @return string 
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Set password
     *
     * @param string $password
     * @return User
     */
    public function setPassword($password)
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Get password
     *
     * @return string 
     */
    public function getPassword()
    {
        return $this->password;
    }

    /**
     * Set createdAt
     *
     * @param \DateTime $createdAt
     * @return User
     */
    public function setCreatedAt($createdAt)
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * Get createdAt
     *
     * @return \DateTime 
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * Add requirement
     *
     * @param \Site\Bundle\PlatformBundle\Entity\Requirement $requirement
     * @return User
     */
    public function addRequirement(\Site\Bundle\PlatformBundle\Entity\Requirement $requirement)
    {
        $this->requirement[] = $requirement;

        return $this;
    }

    /**
     * Remove requirement
     *
     * @param \Site\Bundle\PlatformBundle\Entity\Requirement $requirement
     */
    public function removeRequirement(\Site\Bundle\PlatformBundle\Entity\Requirement $requirement)
    {
        $this->requirement->removeElement($requirement);
    }

    /**
     * Get requirement
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getRequirement()
    {
        return $this->requirement;
    }

    /**
     * Set department
     *
     * @param string $department
     * @return User
     */
    public function setDepartment($department)
    {
        $this->department = $department;

        return $this;
    }

    /**
     * Get department
     *
     * @return string 
     */
    public function getDepartment()
    {
        return $this->department;
    }

    /**
     * Set location
     *
     * @param string $location
     * @return User
     */
    public function setLocation($location)
    {
        $this->location = $location;

        return $this;
    }

    /**
     * Get location
     *
     * @return string 
     */
    public function getLocation()
    {
        return $this->location;
    }

    /**
     * Set phone
     *
     * @param string $phone
     * @return User
     */
    public function setPhone($phone)
    {
        $this->phone = $phone;

        return $this;
    }

    /**
     * Get phone
     *
     * @return string 
     */
    public function getPhone()
    {
        return $this->phone;
    }

    /**
     * Set hupuAccount
     *
     * @param string $hupuAccount
     * @return User
     */
    public function setHupuAccount($hupuAccount)
    {
        $this->hupuAccount = $hupuAccount;

        return $this;
    }

    /**
     * Get hupuAccount
     *
     * @return string 
     */
    public function getHupuAccount()
    {
        return $this->hupuAccount;
    }




    public function getSalt()
    {
        // you *may* need a real salt depending on your encoder
        // see section on salt below
        return null;
    }



    /**
     * @inheritDoc
     */
    public function getRoles()
    {
        return array('ROLE_USER');
    }

    /**
     * @inheritDoc
     */
    public function eraseCredentials()
    {
    }

    /**
     * @see \Serializable::serialize()
     */
    public function serialize()
    {
        return serialize(array(
            $this->id,
            $this->username,
            $this->password,
            // see section on salt below
            // $this->salt,
        ));
    }

    /**
     * @see \Serializable::unserialize()
     */
    public function unserialize($serialized)
    {
        list (
            $this->id,
            $this->username,
            $this->password,
            // see section on salt below
            // $this->salt
            ) = unserialize($serialized);
    }

    /**
     * Set username
     *
     * @param string $username
     * @return User
     */
    public function setUsername($username)
    {
        $this->username = $username;

        return $this;
    }

    /**
     * Get username
     *
     * @return string 
     */
    public function getUsername()
    {
        return $this->username;
    }






    /**
     * Set username
     *
     * @param string $username
     * @return User
     */
    public function setName($username)
    {
        $this->username = $username;

        return $this;
    }

    /**
     * Get username
     *
     * @return string
     */
    public function getName()
    {
        return $this->username;
    }

    /**
     * Add resource
     *
     * @param \Site\Bundle\PlatformBundle\Entity\Resource $resource
     * @return User
     */
    public function addResource(\Site\Bundle\PlatformBundle\Entity\Resource $resource)
    {
        $this->resource[] = $resource;

        return $this;
    }

    /**
     * Remove resource
     *
     * @param \Site\Bundle\PlatformBundle\Entity\Resource $resource
     */
    public function removeResource(\Site\Bundle\PlatformBundle\Entity\Resource $resource)
    {
        $this->resource->removeElement($resource);
    }

    /**
     * Get resource
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getResource()
    {
        return $this->resource;
    }

    /**
     * Get getDepartmentZh
     *
     * @return string
     */
    public function getDepartmentZh()
    {
        $department = MyConst::$departmentZhArr;
        if ($this->department) {
            return $department[$this->department];
        } else {
            return '';
        }
    }

    /**
     * Get getLocationZh
     *
     * @return string
     */
    public function getLocationZh()
    {
        $arr = MyConst::$officeLocationZhArr;
        if ($this->location) {
            return $arr[$this->location];
        } else {
            return '';
        }
    }
}

src/Site/Bundle/PlatformBundle/Controller/UserController.php
<?php

namespace Site\Bundle\PlatformBundle\Controller;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Site\Bundle\PlatformBundle\Entity\User;
use Site\Bundle\PlatformBundle\Form\UserType;

/**
 * User controller.
 *
 * @Route("/user")
 */
class UserController extends Controller
{

    /**
     * Lists all User entities.
     *
     * @Route("/", name="user")
     * @Method("GET")
     * @Template()
     */
    public function indexAction()
    {
        $em = $this->getDoctrine()->getManager();

        $entities = $em->getRepository('SitePlatformBundle:User')->findAll();
        return array(
            'entities' => $entities,
        );
    }

    /**
     * Creates a new User entity.
     *
     * @Route("/", name="user_create")
     * @Method("POST")
     * @Template("SitePlatformBundle:User:new.html.twig")
     */
    public function createAction(Request $request)
    {
        $entity = new User();
        $form = $this->createCreateForm($entity);
        $form->handleRequest($request);

        if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($entity);
            $em->flush();

            return $this->redirect($this->generateUrl('user_show', array('id' => $entity->getId())));
        }

        return array(
            'entity' => $entity,
            'form' => $form->createView(),
        );
    }

    /**
     * Creates a form to create a User entity.
     *
     * @param User $entity The entity
     *
     * @return \Symfony\Component\Form\Form The form
     */
    private function createCreateForm(User $entity)
    {
        $form = $this->createForm(new UserType(), $entity, array(
            'action' => $this->generateUrl('user_create'),
            'method' => 'POST',
        ));

       // $form->add('submit', 'submit', array('label' => 'Create'));

        return $form;
    }

    /**
     * Displays a form to create a new User entity.
     *
     * @Route("/new", name="user_new")
     * @Method("GET")
     * @Template()
     */
    public function newAction()
    {
        $entity = new User();
        $form = $this->createCreateForm($entity);

        return array(
            'entity' => $entity,
            'form' => $form->createView(),
        );
    }

    /**
     * Finds and displays a User entity.
     *
     * @Route("/{id}", name="user_show")
     * @Method("GET")
     * @Template()
     */
    public function showAction($id)
    {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('SitePlatformBundle:User')->find($id);
        if (!$entity) {
            throw $this->createNotFoundException('Unable to find User entity.');
        }

        $deleteForm = $this->createDeleteForm($id);

        return array(
            'entity' => $entity,
            'delete_form' => $deleteForm->createView(),
        );
    }

    /**
     * Displays a form to edit an existing User entity.
     *
     * @Route("/{id}/edit", name="user_edit")
     * @Method("GET")
     * @Template()
     */
    public function editAction($id)
    {
        $securityContext = $this->container->get('security.context');
        $user = $securityContext->getToken()->getUser();

        if(($user->getId() != $id ) && ($user->getUserName() !='admin')){
            echo "<script type=\"text/javascript\">";
            echo "alert(\"没有权限!\")";
            echo "</script>";

            return $this->redirect($this->generateUrl('user'));

        }
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('SitePlatformBundle:User')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find User entity.');
        }

        $editForm = $this->createEditForm($entity);
        $deleteForm = $this->createDeleteForm($id);

        return array(
            'entity' => $entity,
            'edit_form' => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
        );
    }

    /**
     * Creates a form to edit a User entity.
     *
     * @param User $entity The entity
     *
     * @return \Symfony\Component\Form\Form The form
     */
    private function createEditForm(User $entity)
    {
        $form = $this->createForm(new UserType(), $entity, array(
            'action' => $this->generateUrl('user_update', array('id' => $entity->getId())),
            'method' => 'PUT',
        ));

        //  $form->add('submit', 'submit', array('label' => 'Update'));

        return $form;
    }

    /**
     * Edits an existing User entity.
     *
     * @Route("/{id}", name="user_update")
     * @Method("PUT")
     * @Template("SitePlatformBundle:User:edit.html.twig")
     */
    public function updateAction(Request $request, $id)
    {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('SitePlatformBundle:User')->find($id);

        $originPassWord = $entity->getPassword();

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find User entity.');
        }

        $deleteForm = $this->createDeleteForm($id);
        $editForm = $this->createEditForm($entity);
        $editForm->handleRequest($request);


//        $factory = $this->get('security.encoder_factory');
//        $encoder = $factory->getEncoder($entity);

        if ($editForm->isValid()) {

            $newPassWord = $editForm->get('password')->getData();


            if (empty($newPassWord)) {
                $entity->setPassword($originPassWord);
            } else {

                $factory = $this->get('security.encoder_factory');
                $user = new User();
                $encoder = $factory->getEncoder($user);
                $password = $encoder->encodePassword($newPassWord, $user->getSalt());
//var_dump($password);exit;

                $entity->setPassword($password);
            }

            $em->flush();

            return $this->redirect($this->generateUrl('user_show', array('id' => $id))); //
        }

        return array(
            'entity' => $entity,
            'edit_form' => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
        );
    }

    /**
     * Deletes a User entity.
     *
     * @Route("/{id}", name="user_delete")
     * @Method("DELETE")
     */
    public function deleteAction(Request $request, $id)
    {
        $form = $this->createDeleteForm($id);
        $form->handleRequest($request);

        if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $entity = $em->getRepository('SitePlatformBundle:User')->find($id);

            if (!$entity) {
                throw $this->createNotFoundException('Unable to find User entity.');
            }

            $em->remove($entity);
            $em->flush();
        }

        return $this->redirect($this->generateUrl('user'));
    }

    /**
     * Creates a form to delete a User entity by id.
     *
     * @param mixed $id The entity id
     *
     * @return \Symfony\Component\Form\Form The form
     */
    private function createDeleteForm($id)
    {
        return $this->createFormBuilder()
            ->setAction($this->generateUrl('user_delete', array('id' => $id)))
            ->setMethod('DELETE')
            ->add('submit', 'submit', array('label' => 'Delete'))
            ->getForm();
    }
}

src/Site/Bundle/PlatformBundle/Resources/views/User/edit.html.twig
{% extends 'SitePlatformBundle::layout.html.twig' %}

{% block content %}

    <form class="addDemond" action="{{ edit_form.vars.action }}" method="POST">
        <input type="hidden" name="_method" value="{{ edit_form.vars.method }}">

        <h2>系统管理>用户管理>更新用户</h2>

        <div class="demond-theme">
            {{ form_errors(edit_form) }}
            <strong>真实姓名：</strong><br>
            {{ form_widget(edit_form.name, {'attr': {'class': 'theme'} }) }}
        </div>
        <div class="demond-item">
            <strong>所属部门：</strong><br>
            {{ form_widget(edit_form.department , {'attr': {'class': 'item'} }) }}
        </div>
        <div class="demond-company">
            <strong>办公地点：</strong><br>
            {{ form_widget(edit_form.location , {'attr': {'class': 'company'} }) }}
        </div>
        <div class="demond-theme">
            <strong>虎扑账号：</strong><br>
            {{ form_widget(edit_form.hupuAccount , {'attr': {'class': 'zhanghao'} }) }}
        </div>
        <div class="demond-theme">
            <strong>账号密码：(不修改留空)</strong><br>
            {{ form_widget(edit_form.password.first, {'attr': {'class': 'pwd'} }) }}
        </div>
        <div class="demond-theme">
            <strong>确认密码：(不修改留空)</strong><br>
            {{ form_widget(edit_form.password.second, {'attr': {'class': 'confirm_pwd'} }) }}
        </div>

        <div class="demond-theme">
            <strong>手机号：</strong><br>
            {{ form_widget(edit_form.phone , {'attr': {'class': 'phone'} }) }}
        </div>
        <div class="demond-theme">
            <strong>E-mail：</strong><br>
            {{ form_widget(edit_form.email , {'attr': {'class': 'email'} }) }}
        </div>
        <!-- <div class="demond-company">
            <strong>隶属角色：</strong><br>
            <select name="company" id="" class="company">
                <option value="">管理员</option>
                <option value="">普通用户</option>
            </select>
        </div> -->
        {{ form_rest(edit_form) }}
        <div class="demond-btn">
            <input type="submit" class="add" value="更新">
            <a href="{{ path('user') }}" class="back">返回</a>

        </div>
    </form>

{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script>
        function trim(str){ //删除左右两端的空格
            return str.replace(/(^\s*)|(\s*$)/g, "");
        }

        //判断两次密码输入是否一致
        $('.add').click(function () {
            /*var val1 = trim($('.pwd').val());
            var val2 = trim($('.confirm_pwd').val());
            if (val1 == '' || val2 == '') {
                alert('密码不能为空');
                return false;

            }
            if (val1 != val2) {
                alert('两次输入的密码不正确');
                return false;
            }*/

            var theme = $.trim( $('.theme').val() );
       
            var item = $('.item').find("option:selected").val();
            var company = $('.company').find("option:selected").val();
            var zhanghao = $.trim( $('.zhanghao').val() );
            var phone = $.trim( $('.phone').val() );
            var email = $.trim( $('.email').val() );

            var reg = /^1(3[4-9]|5[012789]|8[78])\d{8}$/;
            var reg1 = /^18[09]\d{8}$/;
            var reg2 = /^1(3[0-2]|5[56]|8[56])\d{8}$/;
            
            var reg3 = /^[a-zA-Z0-9_-]+@[a-zA-Z0-9_-]+(\.[a-zA-Z0-9_-]+)+$/;

            if (theme == '' || item == '' || company == '' || zhanghao==''||phone==''||email=='') {
                alert('请完整填写信息');

                return false;
            }else if( !(reg.test(phone)||reg1.test(phone)||reg2.test(phone)) ){
                alert('请填写正确的手机号码');

                return false;
            }else if( !(reg3.test(email)) ){
                alert('请填写正确的邮箱');

                return false;
            }

        })
    </script>

{% endblock %}

src/Site/Bundle/PlatformBundle/Resources/views/User/index.html.twig
{% extends 'SitePlatformBundle::layout.html.twig' %}

{% block content %}
    <div class="demand-con">
        <a href="{{ path('user_new') }}" class="addDemand">新增</a>
    <table border='0' cellspacing='0' cellpadding='0' width="100%" class="demand-table">
        <tr>
            <th width="10%">ID</th>
            <th width="20%">姓名</th>
            <th width="15%">Email</th>
            <th width="20%">手机</th>
            <th width="10%">部门</th>
            <th width="10%">创建日期</th>
            <th width="15%">编辑栏</th>
        </tr>

        {% for entity in entities %}
            <tr>
                <td>{{ entity.id }}</td>
                <td>{{ entity.username }}</td>
                <td>{{ entity.email }}</td>
                <td>{{ entity.phone }}</td>
                <td>{{ entity.departmentZh }}</td>
                <td>{% if entity.createdAt %}{{ entity.createdAt|date('Y-m-d') }}{% endif %}</td>
                <td><a href="{{ path('user_show', { 'id': entity.id }) }}">查看</a>| <a
                            href="{{ path('user_edit', { 'id': entity.id }) }}">编辑</a></td>
            </tr>
        {% endfor %}
    </table>
    </div>

{% endblock %}

src/Site/Bundle/PlatformBundle/Resources/views/User/new.html.twig
{% extends 'SitePlatformBundle::layout.html.twig' %}

{% block content %}

    <form class="addDemond" action="{{ form.vars.action }}" method="POST">
        <input type="hidden" name="_method" value="{{ form.vars.method }}">

        <h2>系统管理><a href="{{ path('user') }}">用户管理</a>>>新增用户</h2>

        <div class="demond-theme">
            {{ form_errors(form) }}
            <strong>真实姓名：</strong><br>
            {{ form_widget(form.name, {'attr': {'class': 'theme'} }) }}
        </div>
        <div class="demond-item">
            <strong>所属部门：</strong><br>
            {{ form_widget(form.department , {'attr': {'class': 'item'} }) }}
        </div>
        <div class="demond-company">
            <strong>办公地点：</strong><br>
            {{ form_widget(form.location , {'attr': {'class': 'company'} }) }}
        </div>
        <div class="demond-theme">
            <strong>虎扑账号：</strong><br>
            {{ form_widget(form.hupuAccount , {'attr': {'class': 'zhanghao'} }) }}
        </div>
        <div class="demond-theme">
            <strong>账号密码：</strong><br>
            {{ form_widget(form.password.first, {'attr': {'class': 'pwd'} }) }}
        </div>
        <div class="demond-theme">
            <strong>确认密码</strong><br>
            {{ form_widget(form.password.second, {'attr': {'class': 'confirm_pwd'} }) }}
        </div>

        <div class="demond-theme">
            <strong>手机号：</strong><br>
            {{ form_widget(form.phone , {'attr': {'class': 'phone'} }) }}
        </div>
        <div class="demond-theme">
            <strong>E-mail：</strong><br>
            {{ form_widget(form.email , {'attr': {'class': 'email'} }) }}
        </div>
        <!-- <div class="demond-company">
            <strong>隶属角色：</strong><br>
            <select name="company" id="" class="company">
                <option value="">管理员</option>
                <option value="">普通用户</option>
            </select>
        </div> -->
        {{ form_rest(form) }}
        <div class="demond-btn">
            <input type="submit" class="add" value="创建">
            <a href="{{ path('user') }}" class="back">返回</a>

        </div>
    </form>

{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script>

        $('.add').click(function () {
            var val1 = $.trim($('.pwd').val());
            var val2 = $.trim($('.confirm_pwd').val());
           

            var theme = $.trim( $('.theme').val() );
       
            var item = $('.item').find("option:selected").val();
            var company = $('.company').find("option:selected").val();
            var zhanghao = $.trim( $('.zhanghao').val() );
            var phone = $.trim( $('.phone').val() );
            var email = $.trim( $('.email').val() );

            var reg = /^1(3[4-9]|5[012789]|8[78])\d{8}$/;
            var reg1 = /^18[09]\d{8}$/;
            var reg2 = /^1(3[0-2]|5[56]|8[56])\d{8}$/;
            
            var reg3 = /^[a-zA-Z0-9_-]+@[a-zA-Z0-9_-]+(\.[a-zA-Z0-9_-]+)+$/;

            if (theme == '' || item == '' || company == '' || zhanghao==''||phone==''||email=='') {
                alert('请完整填写信息');

                return false;
            }
            else if(val1 == '' || val2 == ''){
                alert('密码不能为空');
                return false;
            }
            else if(val1 != val2) {
                alert('两次输入的密码不正确');
                return false;
            }
            else if( !(reg.test(phone)||reg1.test(phone)||reg2.test(phone)) ){
                alert('请填写正确的手机号码');

                return false;
            }else if( !(reg3.test(email)) ){
                alert('请填写正确的邮箱');

                return false;
            }

        })
    </script>

{% endblock %}

src/Site/Bundle/PlatformBundle/Resources/views/User/show.html.twig
{% extends 'SitePlatformBundle::layout.html.twig' %}

{% block title %}虎扑协作平台{% endblock %}

{% block content %}
    <div class="addDemond">
        <h2>系统管理>查看用户</h2>

        <div class="show-theme">
            <strong>真实姓名：</strong>

            <p>{{ entity.name }}</p>
        </div>
        <div class="show-item">
            <strong>所属部门：</strong>

            <p>{{ entity.departmentZh }}</p>
        </div>
        <div class="show-company">
            <strong>办公地点：</strong>

            <p>{{ entity.locationZh }}</p>
        </div>
        <div class="show-area">
            <strong>虎扑账号：</strong>

            <p>
                {{ entity.hupuAccount }}
            </p>
        </div>

        <div class="show-people">
            <strong>手机号：</strong>

            <p>{{ entity.phone }}</p>
        </div>
        <div class="show-people">
            <strong>E-mail：</strong>

            <p>{{ entity.email }}</p>
        </div>

        <div class="demond-btn">

            <a href="{{ path('user') }}" class="del">返回</a>

        </div>
    </div>

{% endblock %}