src/Site/Bundle/PlatformBundle/Entity/Requirement.php
<?php

namespace Site\Bundle\PlatformBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Site\Bundle\PlatformBundle\lib\MyConst;

/**
 * Requirement
 *
 * @ORM\Table(name="requirement")
 * @ORM\Entity(repositoryClass="Site\Bundle\PlatformBundle\Entity\RequirementRepository")
 */
class Requirement
{

    /**
     * Constructs a new instance of User
     */
    public function __construct()
    {
        $this->updateTime = new \DateTime();
    }

    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string //需求主题
     *
     * @ORM\Column(name="subject", type="string", length=255)
     */
    private $subject;

    /**
     * @var string //运动项目
     *
     * @ORM\Column(name="sports", type="string", length=255)
     */
    private $sports;


    /**
     * @var string //单位性质
     *
     * @ORM\Column(name="company_type", type="string", length=255)
     */
    private $companyType;

    /**
     * @var string
     *
     * @ORM\Column(name="country", type="string", length=255)
     */
    private $country;


    /**
     * @var string
     *
     * @ORM\Column(name="province", type="string", length=255)
     */
    private $province;

    /**
     * @var string
     *
     * @ORM\Column(name="city", type="string", length=255)
     */
    private $city;


    /**
     * @var string //需求简述
     *
     * @ORM\Column(name="description", type="text")
     */
    private $description;

    /**
     * @var \DateTime
     *
     * //更新时间
     *
     * @ORM\Column(name="update_time", type="datetime")
     */
    private $updateTime;


    /**
     * @var \DateTime
     *
     * //报告时间
     *
     * @ORM\Column(name="report_time", type="date")
     */
    private $reportTime;


    /**
     * @var object //联系人
     *
     * @ORM\ManyToOne(targetEntity="User", inversedBy="requirement")
     * @ORM\JoinColumn(name="contact_id", referencedColumnName="id")
     */
    private $contact;


    /**
     * @var string //部门
     *
     * @ORM\Column(name="department", type="string", length=255)
     */
    private $department;

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set subject
     *
     * @param string $subject
     * @return Requirement
     */
    public function setSubject($subject)
    {
        $this->subject = $subject;

        return $this;
    }

    /**
     * Get subject
     *
     * @return string
     */
    public function getSubject()
    {

        return $this->subject;

    }

    /**
     * Get subject
     *
     * @return string
     */
    public function getFormatSubject()
    {

        if (!empty($this->subject) && (mb_strlen($this->subject, 'utf-8') > 15)) {
            return mb_strcut($this->subject, 0, 40, 'utf-8') . '...';
        }

        return $this->subject;

    }

    /**
     * Set sports
     *
     * @param string $sports
     * @return Requirement
     */
    public function setSports($sports)
    {
        $this->sports = $sports;

        return $this;
    }

    /**
     * Get sports
     *
     * @return string
     */
    public function getSports()
    {
        return $this->sports;
    }


    /**
     * Set province
     *
     * @param string $province
     * @return Requirement
     */
    public function setProvince($province)
    {
        $this->province = $province;

        return $this;
    }

    /**
     * Get province
     *
     * @return string
     */
    public function getProvince()
    {
        return $this->province;
    }

    /**
     * Set city
     *
     * @param string $city
     * @return Requirement
     */
    public function setCity($city)
    {
        $this->city = $city;

        return $this;
    }

    /**
     * Get city
     *
     * @return string
     */
    public function getCity()
    {
        return $this->city;
    }

    /**
     * Set description
     *
     * @param string $description
     * @return Requirement
     */
    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Get description
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Set updateTime
     *
     * @param \DateTime $updateTime
     * @return Requirement
     */
    public function setUpdateTime($updateTime)
    {
        $this->updateTime = $updateTime;

        return $this;
    }

    /**
     * Get updateTime
     *
     * @return \DateTime
     */
    public function getUpdateTime()
    {
        return $this->updateTime;
    }

    /**
     * Set reportTime
     *
     * @param \DateTime $reportTime
     * @return Requirement
     */
    public function setReportTime($reportTime)
    {
        $this->reportTime = new \DateTime($reportTime);

        return $this;
    }

    /**
     * Get reportTime
     *
     * @return \DateTime
     */
    public function getReportTime()
    {
        if ($this->reportTime) {
            return date_format($this->reportTime, 'Y-m-d');
        }
        return $this->reportTime;
    }

    /**
     * Set contact
     *
     * @param \Site\Bundle\PlatformBundle\Entity\User $contact
     * @return Requirement
     */
    public function setContact(\Site\Bundle\PlatformBundle\Entity\User $contact = null)
    {
        $this->contact = $contact;

        return $this;
    }

    /**
     * Get contact
     *
     * @return \Site\Bundle\PlatformBundle\Entity\User
     */
    public function getContact()
    {
        return $this->contact;
    }


    /**
     * Get sports for chinese
     *
     * @return string
     */
    public function getSportsZh()
    {
        $sports = MyConst::$sportsZhArr;
        if ($this->sports) {
            return $sports[$this->sports];
        } else {
            return '';
        }
    }


    /**
     * Get getDepartmentZh
     *
     * @return string
     */
    public function getDepartmentZh()
    {
        $department = MyConst::$departmentZhArr;
        if ($this->department) {
            return $department[$this->department];
        } else {
            return '';
        }
    }


    /**
     * Get getCompanyTypeZh
     *
     * @return string
     */
    public function getCompanyTypeZh()
    {
        $arr = MyConst::$companyTypeZhArr;
        if ($this->companyType) {
            return $arr[$this->companyType];
        } else {
            return '';
        }
    }

    /**
     * Set country
     *
     * @param string $country
     * @return Requirement
     */
    public function setCountry($country)
    {
        $this->country = $country;

        return $this;
    }

    /**
     * Get country
     *
     * @return string
     */
    public function getCountry()
    {
        return $this->country;
    }

    /**
     * Set department
     *
     * @param string $department
     * @return Requirement
     */
    public function setDepartment($department)
    {
        $this->department = $department;

        return $this;
    }

    /**
     * Get department
     *
     * @return string
     */
    public function getDepartment()
    {
        return $this->department;
    }

    /**
     * Set companyType
     *
     * @param string $companyType
     * @return Requirement
     */
    public function setCompanyType($companyType)
    {
        $this->companyType = $companyType;

        return $this;
    }

    /**
     * Get companyType
     *
     * @return string
     */
    public function getCompanyType()
    {
        return $this->companyType;
    }
}

src/Site/Bundle/PlatformBundle/Controller/RequirementController.php
<?php

namespace Site\Bundle\PlatformBundle\Controller;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Site\Bundle\PlatformBundle\Entity\Requirement;
use Site\Bundle\PlatformBundle\Form\RequirementType;
use Site\Bundle\PlatformBundle\lib\Page;

/**
 * Requirement controller.
 *
 * @Route("/requirement")
 */
class RequirementController extends Controller
{

    /**
     * Lists all Requirement entities.
     *
     * @Route("/p/{page}/", name="requirement",defaults={"page" = 1},requirements={"page" = "\d*"})
     * @Method("GET")
     * @Template()
     */
    public function indexAction(Request $request,$page)
    {
        $em = $this->getDoctrine()->getManager();

        $defaultData = array('keywords' => '请输入关键字查询');


        $form = $this->get('site.common.controller')->createSearchForm($defaultData);


        $formData = $request->query->get('form');

        $params = $this->filterSearchData($formData);

        /*参数*/
        $count = count($em->getRepository('SitePlatformBundle:Requirement')->findAll());
        $limit = 10;
        $offset = ($page-1) * $limit;

        if (empty($params)) {

            $entities = $em->getRepository('SitePlatformBundle:Requirement')->findBy(
                array(),
                array('updateTime' => 'DESC'),
                $limit,
                $offset
            );

        } else {

            // var_dump($params);

            $entities = $em->getRepository('SitePlatformBundle:Requirement')->search($params, $offset, $limit);
            $count = count($entities);
            $entities = array_slice($entities,$offset,$offset+$limit);
        };

        $config = array(
            'total_rows' => $count,
            'per_page' => $limit,
            'num_links' => 3,
            'curr_page' => $page,
            'url_rule' => "#(/requirement/p/)\d+/?#iU",
            'page_container_tag_style'=>'pageWrap',
            'prev_tag_style'=>'prev',
            'next_tag_style'=>'next',
        );


        $paging = new Page($config);
        $pageHtml = $paging->display();

        return array(
            'entities' => $entities,
            'form' => $form,
            'pageHtml' => $pageHtml
        );

    }

    //过滤
    protected function filterSearchData($data)
    {
        if(empty($data)){
            return array();
        }

        $data = array_filter($data);

        if ($data['keywords'] == '请输入关键字查询') {
            unset($data['keywords']);
        }
        if ($data['country'] == '国家') {
            unset($data['country']);
        }
        if ($data['province'] == '省份/州') {
            unset($data['province']);
        }
        if ($data['city'] == '城市') {
            unset($data['city']);
        }
        return $data;
    }

    /**
     * Creates a new Requirement entity.
     *
     * @Route("/", name="requirement_create")
     * @Method("POST")
     * @Template("SitePlatformBundle:Requirement:new.html.twig")
     */
    public function createAction(Request $request)
    {
        $entity = new Requirement();
        $form = $this->createCreateForm($entity);
        $form->handleRequest($request);
       // var_dump($form);exit;

        if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($entity);
            $em->flush();

            return $this->redirect($this->generateUrl('requirement_show', array('id' => $entity->getId())));
        }

        return array(
            'entity' => $entity,
            'form' => $form->createView(),
        );
    }

    /**
     * Creates a form to create a Requirement entity.
     *
     * @param Requirement $entity The entity
     *
     * @return \Symfony\Component\Form\Form The form
     */
    private function createCreateForm(Requirement $entity)
    {
        $form = $this->createForm(new RequirementType(), $entity, array(
            'action' => $this->generateUrl('requirement_create'),
            'method' => 'POST',
        ));

       // $form->add('submit', 'submit', array('label' => 'Create'));

        return $form;
    }

    /**
     * Displays a form to create a new Requirement entity.
     *
     * @Route("/new", name="requirement_new")
     * @Method("GET")
     * @Template()
     */
    public function newAction()
    {
        $entity = new Requirement();
        $form = $this->createCreateForm($entity);

        return array(
            'entity' => $entity,
            'form' => $form->createView(),
        );
    }

    /**
     * Finds and displays a Requirement entity.
     *
     * @Route("/{id}", name="requirement_show")
     * @Method("GET")
     * @Template()
     */
    public function showAction($id)
    {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('SitePlatformBundle:Requirement')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Requirement entity.');
        }

        $deleteForm = $this->createDeleteForm($id);
        return array(
            'entity' => $entity,
            'delete_form' => $deleteForm->createView(),
        );
    }

    /**
     * Displays a form to edit an existing Requirement entity.
     *
     * @Route("/{id}/edit", name="requirement_edit")
     * @Method("GET")
     * @Template()
     */
    public function editAction($id)
    {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('SitePlatformBundle:Requirement')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Requirement entity.');
        }

        $editForm = $this->createEditForm($entity);
        $deleteForm = $this->createDeleteForm($id);

        return array(
            'entity' => $entity,
            'edit_form' => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
        );
    }

    /**
     * Creates a form to edit a Requirement entity.
     *
     * @param Requirement $entity The entity
     *
     * @return \Symfony\Component\Form\Form The form
     */
    private function createEditForm(Requirement $entity)
    {
        $form = $this->createForm(new RequirementType(), $entity, array(
            'action' => $this->generateUrl('requirement_update', array('id' => $entity->getId())),
            'method' => 'PUT',
        ));

        //$form->add('submit', 'submit', array('label' => '更新'));

        return $form;
    }

    /**
     * Edits an existing Requirement entity.
     *
     * @Route("/{id}", name="requirement_update")
     * @Method("PUT")
     * @Template("SitePlatformBundle:Requirement:edit.html.twig")
     */
    public function updateAction(Request $request, $id)
    {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('SitePlatformBundle:Requirement')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Requirement entity.');
        }
        $entity->setUpdateTime(new \DateTime());
        $deleteForm = $this->createDeleteForm($id);
        $editForm = $this->createEditForm($entity);
        $editForm->handleRequest($request);
     //   var_dump(111111);exit;
        if ($editForm->isValid()) {
            $em->flush();

            //return $this->redirect($this->generateUrl('requirement_edit', array('id' => $id)));
            return $this->redirect($this->generateUrl('requirement_show', array('id' => $id)));
        }

        return array(
            'entity' => $entity,
            'edit_form' => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
        );
    }

    /**
     * Deletes a Requirement entity.
     *
     * @Route("/{id}", name="requirement_delete")
     * @Method("DELETE")
     */
    public function deleteAction(Request $request, $id)
    {
        $form = $this->createDeleteForm($id);
        $form->handleRequest($request);

        if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $entity = $em->getRepository('SitePlatformBundle:Requirement')->find($id);

            if (!$entity) {
                throw $this->createNotFoundException('Unable to find Requirement entity.');
            }

            $em->remove($entity);
            $em->flush();
        }

        return $this->redirect($this->generateUrl('requirement'));
    }

    /**
     * Creates a form to delete a Requirement entity by id.
     *
     * @param mixed $id The entity id
     *
     * @return \Symfony\Component\Form\Form The form
     */
    private function createDeleteForm($id)
    {
        return $this->createFormBuilder()
            ->setAction($this->generateUrl('requirement_delete', array('id' => $id)))
            ->setMethod('DELETE')
            ->add('submit', 'submit', array('label' => '删除'))
            ->getForm();
    }
}

src/Site/Bundle/PlatformBundle/Resources/views/Requirement/edit.html.twig
{% extends 'SitePlatformBundle::layout.html.twig' %}

{% block content %}

    <form class="addDemond" action="{{ edit_form.vars.action }}" method="POST">
        <input type="hidden" name="_method" value="{{ edit_form.vars.method }}">

        <h2>
            <a href="{{ path('requirement') }}">需求管理</a> >更新需求
        </h2>

        <div class="demond-theme">
            <strong>需求主题：</strong><br>
            {{ form_widget(edit_form.subject , {'attr': {'class': 'theme'} }) }}
        </div>
        <div class="demond-item">
            <strong>运动项目：</strong><br>
            {{ form_widget(edit_form.sports , {'attr': {'class': 'item'} }) }}
        </div>
        <div class="demond-company">
            <strong>单位性质：</strong><br>
            {{ form_widget(edit_form.companyType, {'attr': {'class': 'company'} }) }}
        </div>
        <div class="selWrap">
            <div class="sel1">
                <strong>国家/地区：</strong><br>
                <select name="country" id="country" class="liandong"></select>
            </div>
            <div class="sel2">
                <strong>省/州：</strong><br>
                <select name="province" id="province" class="liandong"></select>
            </div>
            <div class="sel3">
                <strong>市：</strong><br>
                <select name="city" id="city" class="liandong"></select>
            </div>
        </div>
        <div class="demond-desc">
            <strong>需求简述：</strong><br>
            {{ form_widget(edit_form.description , {'attr': {'style': 'width:300px ; height:120px' } }) }}
        </div>
        <div class="selWrap2">
            <div class="sel4">
                <strong>联络人：</strong><br>
                {{ form_widget(edit_form.contact , {'attr': {'class': 'liandong'} }) }}
            </div>
            <div class="sel5">
                <strong>部门：</strong><br>
                {{ form_widget(edit_form.department , {'attr': {'class': 'liandong'} }) }}
            </div>
        </div>
        <div class="demond-time">
            <strong>反馈时间：</strong>
            <br/>
            {{ form_widget(edit_form.reportTime , {'attr': {'class': 'Wdate'} }) }}
        </div>

        {{ form_rest(edit_form) }}
        <div class="demond-btn">
            <input type="submit" class="add" value="更新">
            <a href="{{ path('requirement') }}" class="back">
                返回
            </a>

        </div>
    </form>
{% endblock %}


{% block javascripts %}
    {{ parent() }}
    {% javascripts
    '@SitePlatformBundle/Resources/public/js/area.js' %}
    <script src="{{ asset_url }}" type="text/javascript"></script>

    <script>
        var s = ["country", "province", "city"];//三个select的id
        var country_id = '#' + '{{ edit_form.country.vars.id }}';
        var province_id = '#' + '{{ edit_form.province.vars.id }}';
        var city_id = '#' + '{{ edit_form.city.vars.id }}';

        _init_area('{{ edit_form.country.vars.data }}', '{{ edit_form.province.vars.data }}', '{{ edit_form.city.vars.data }}');

        $('.add').bind('click', function () {
            country = $("#country").find("option:selected").val();
            province = $("#province").find("option:selected").val();
            city = $("#city").find("option:selected").val();

            var theme = $.trim( $('.theme').val() );
       
            var item = $('.item').find("option:selected").val();
            var company = $('.company').find("option:selected").val();
            var desc = $.trim( $('.demond-desc').find('textarea').val() );
            var bumen = $('.sel5').find('.liandong').find("option:selected").val();
            var date = $.trim( $('.Wdate').val() );
            
            if (country == '国家' || province == '省份/周' || city == '城市' || theme == '' || item == '' || company == '' || desc==''||bumen==''||date=='') {
                alert('请完整填写信息');

                return false;
            }
           
            $(country_id).val($("#country").find("option:selected").val());
            $(province_id).val($("#province").find("option:selected").val());
            $(city_id).val($("#city").find("option:selected").val());
            // alert($(country_id).val() + ' ' + $(province_id).val() + ' ' + $(city_id).val());



        })

    </script>
    {% endjavascripts %}

{% endblock %}

src/Site/Bundle/PlatformBundle/Resources/views/Requirement/index.html.twig
{% extends 'SitePlatformBundle::layout.html.twig' %}

{% block title %}虎扑协作平台{% endblock %}

{% block content %}

    <div class="demand-con" xmlns="http://www.w3.org/1999/html">
        <div class="searchBar">
            <a href="{{ path('requirement_new') }}" class="addDemand">+ 新增需求</a>

            <form action="{{ path('requirement') }}" method="get" {{ form_enctype(form) }}>

                {{ form_errors(form.sports) }}
                {{ form_widget(form.sports , {'attr': {'class': 'item'} }) }}

                {{ form_errors(form.updateTimeMin) }}
                {{ form_widget(form.updateTimeMin , {'attr': {'class': 'date'} }) }}

                {{ form_errors(form.updateTimeMax) }}
                {{ form_widget(form.updateTimeMax , {'attr': {'class': 'date'} }) }}


                {{ form_errors(form.country) }}
                {{ form_widget(form.country , {'attr': {'class': 'liandong'} }) }}

                {{ form_errors(form.province) }}
                {{ form_widget(form.province, {'attr': {'class': 'liandong'} }) }}


                {{ form_errors(form.city) }}
                {{ form_widget(form.city, {'attr': {'class': 'liandong'} }) }}

                {{ form_widget(form.keywords,{'attr': {'class': 'keywords'} }) }}

                <input class="searchBtn" type="submit" value="搜索"/>
            </form>

        </div>
        <table border='0' cellspacing='0' cellpadding='0' width="100%" class="demand-table">
            <tr>
                <th width="10%">更新时间</th>
                <th width="10%">运动项目</th>
                <th width="15%">单位性质</th>
                <th width="10%">所属地区</th>
                <th width="25%">需求主题（点击查看详细）</th>
                <th width="11%">内部联络人</th>
                <th width="8%">反馈时间</th>
                <th width="11%">...</th>
            </tr>
            {% for entity in entities %}
                <tr>
                    <td>{% if entity.updatetime %}{{ entity.updatetime|date('Y-m-d') }}{% endif %}</td>
                    <td>{% if entity.sports %}{{ entity.getSportsZh }}{% endif %}</td>
                    <td>{{ entity.companyTypeZh }}</td>
                    <td>{{ entity.country }}</td>
                    <td><a href="{{ path('requirement_show', { 'id': entity.id }) }}" target="_blank">{{ entity.getFormatSubject }}</a></td>
                    <td>{% if entity.contact %}{{ entity.contact.name }}{% endif %}</td>
                    <td>{% if entity.reporttime %}{{ entity.reporttime|date('Y-m-d') }}{% endif %}</td>

                    <td><a href="{{ path('requirement_edit', { 'id': entity.id }) }}">编辑</a></td>
                </tr>
            {% endfor %}
        </table>

        {{ pageHtml | raw }}

    </div>

{% endblock %}





{% block javascripts %}
    {{ parent() }}
    {% javascripts
    '@SitePlatformBundle/Resources/public/js/area.js'
    %}
    <script src="{{ asset_url }}" type="text/javascript"></script>
    {% endjavascripts %}

    <script>
        _init_area('', '', '');
        $('.keywords').focus(function () {
            if ($(this).val() == '请输入关键字查询') {
                $(this).val('');
            }
        }).blur(function () {
            if ($(this).val() == '') {
                $(this).val('请输入关键字查询');
            }
        })
        $('.del').on('click', function () {
            var show = showVideo.create({
                wid: 400,
                hei: 180
            });
            show.init();
            $('.cover').bind('click', function () {
                $(".popCon,.cover").remove();
            })
            $('.confirm').bind('click', function () {

            })
        })

    </script>

{% endblock %}

src/Site/Bundle/PlatformBundle/Resources/views/Requirement/search.html.twig
{% extends '::base.html.twig' %}

{% block body -%}
    <form action="{{ path('requirement') }}" method ="get" {{ form_enctype(form) }}>
        {{ form_widget(form) }}

        <input type="submit" />
    </form>

    <form action="{{ path('requirement') }}" method="get">
        <ul style="list-style: none;" class="search">
            <li>
                <a href="{{ path('requirement_new') }}">
                    添加
                </a>
            </li>

            <li>需求主题: <input type="text" name="subject" style="width: 100px"/></li>

            <li>客户单位: <input type="text" name="company" style="width: 100px"/></li>

            <li><input type="submit" value="提交"/></li>
        </ul>
    </form>
    <h1>需求列表</h1>

    <table class="records_list">
        <thead>
        <tr>
            <th>需求主题</th>
            <th>客户单位</th>
            <th>客户行业</th>
            <th>Background</th>
            <th>Description</th>
            <th>Starttime</th>
            <th>Endtime</th>
            <th>Status</th>
            <th>分类</th>
            <th>发起人</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        {% for entity in entities %}
            <tr>
                <td><a href="{{ path('requirement_show', { 'id': entity.id }) }}">{{ entity.id }}</a></td>
                <td>{{ entity.subject }}</td>
                <td>{{ entity.company }}</td>
                <td>{{ entity.background }}</td>
                <td>{{ entity.description }}</td>
                <td>{% if entity.startTime %}{{ entity.startTime|date('Y-m-d H:i:s') }}{% endif %}</td>
                <td>{% if entity.endTime %}{{ entity.endTime|date('Y-m-d H:i:s') }}{% endif %}</td>
                <td>{{ entity.statusZh }}</td>
                <td>{{ entity.category }}</td>
                <td>{{ entity.initiator }}</td>
                <td>
                    <ul>
                        <li>
                            <a href="{{ path('requirement_show', { 'id': entity.id }) }}">详细信息</a>
                        </li>
                        <li>
                            <a href="{{ path('requirement_edit', { 'id': entity.id }) }}">编辑</a>
                        </li>
                    </ul>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>


{% endblock %}

src/Site/Bundle/PlatformBundle/Resources/views/Requirement/show.html.twig
{% extends 'SitePlatformBundle::layout.html.twig' %}

{% block content %}
    <div class="addDemond">
        <h2>
            <a href="{{ path('requirement') }}">需求管理</a> >查看需求
        </h2>

        <div class="show-theme">
            <strong>需求主题：</strong>

            <p>{{ entity.subject }}</p>
        </div>
        <div class="show-item">
            <strong>运动项目：</strong>

            <p>{{ entity.getSportsZh }}</p>
        </div>
        <div class="show-company">
            <strong>单位性质：</strong>

            <p>{{ entity.companyTypeZh }}</p>
        </div>
        <div class="show-area">
            <strong>所属地区：</strong>

            <p>
                <span>{{ entity.country }}</span>，
                <span>{{ entity.province }}</span>,
                <span>{{ entity.city }}</span>
            </p>
        </div>
        <div class="show-desc">
            <strong>需求简述：</strong>

            <p>
                {{ entity.description }}
            </p>
        </div>
        <div class="show-people">
            <strong>联络人及部门：</strong>

            <p><span>{{ entity.departmentZh }}</span> -
                <span>{% if entity.contact %}{{ entity.contact.name }}{% endif %}</span></p>
        </div>
        <div class="demond-time">
            <strong>反馈时间：</strong><br>

            <p>{{ entity.reporttime|date('Y-m-d') }}</p>
        </div>
        <div class="demond-btn">

            <form class="deleteForm" action="{{ delete_form.vars.action }}" method="POST">
                <input type="hidden" name="_method" value="{{ delete_form.vars.method }}">
                {{ form_widget(delete_form , {'attr': {'class': 'delete'} }) }}

            </form>

            <a href="{{ path('requirement') }}" class="del">返回</a>

        </div>

    </div>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {% javascripts
    '@SitePlatformBundle/Resources/public/js/video.js' %}
    <script src="{{ asset_url }}" type="text/javascript"></script>

    <script>
        $('.delete button').on('click',function(){
            var show = showVideo.create({
                wid:400,
                hei:180
            });
            show.init();

            $('.cover').bind('click',function(){
                $(".popCon,.cover").remove();
            })
            $('.confirm').bind('click',function(){
                console.log(123);
                $('.deleteForm').submit();
            })
            return false;
        })


    </script>
    {% endjavascripts %}

{% endblock %}